config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  root 'dashboard#home'
  get 'week_day_menu' => 'dashboard#week_day_menu'

  resources :orders

  namespace :api, defaults: { format: :json } do
    resources :orders, only: :index
    resources :sessions, only: [:create, :destroy]
    resources :users, only: :show
  end

  get '*path' => redirect('/')
end

app/views/shared/_header.slim
header
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-brand
          = link_to "Moscow Lunch", root_path
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li= link_to 'WeekDays Menu', week_day_menu_path
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            - if current_user.has_role? :admin
              li = link_to 'Admin Panel', admin_root_path
          li.dropdown
            - if user_signed_in?
              a#drop.dropdown-toggle href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'
                span.glyphicon.glyphicon-user
                  = " " + current_user.name
                  span.caret
              ul.dropdown-menu role='menu' aria-labelledby='drop'
                li= link_to 'Log Out', destroy_user_session_path, :method=>'delete'
                li= link_to 'Edit', edit_user_registration_path
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path

app/views/shared/_main.slim
.container
  .row
    = bootstrap_flash
    = yield

app/views/shared/_social_links.html.slim
= link_to " Google", user_google_oauth2_omniauth_authorize_path