config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  root 'dashboard#home'
  get 'week_day_menu' => 'dashboard#week_day_menu'

  resources :orders

  namespace :api, defaults: { format: :json } do
    resources :orders, only: :index
    resources :sessions, only: [:create, :destroy]
    resources :users, only: :show
  end

  get '*path' => redirect('/')
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id              :integer          not null, primary key
#  total           :decimal(, )
#  user_id         :integer
#  organization_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_orders_on_organization_id  (organization_id)
#  index_orders_on_user_id          (user_id)
#
# Foreign Keys
#
#  fk_rails_f868b47f6a  (user_id => users.id)
#  fk_rails_fe8af6535c  (organization_id => organizations.id)
#

class Order < ActiveRecord::Base
  include Filterable

  before_create :total_price
  before_create :set_organization

  belongs_to :user
  belongs_to :organization
  has_many :item_associations, as: :item_association, dependent: :destroy
  has_many :items, through: :item_associations

  validates :user,  presence: true
  validates :items, presence: true, order_items: true

  scope :date, -> (date) { where created_at: date.beginning_of_day..date.end_of_day }
  scope :organization, -> (organization) { joins(:organization).where('organizations.name like ?', "#{organization}%") }

  private

  def total_price
    self.total = items.map(&:price).sum
  end

  def set_organization
    self.organization = user.organization
  end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < ApplicationController
  before_action :authenticate_with_token!
  respond_to :json

  def index
    params[:date] = params[:date].present? ? params[:date].to_datetime.in_time_zone('Moscow').end_of_day : DateTime.now
    orders = Order.filter(params.slice(:date, :organization))

    respond_with orders
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  responders :flash
  respond_to :html

  before_action :authenticate_user!
  before_action :only_one_order!, only: [:new, :create]

  def index
    params[:date] = params[:date].present? ? params[:date].to_datetime.in_time_zone('Moscow').end_of_day : DateTime.now
    @date = params[:date]
    @orders = Order.filter(params.slice(:date, :organization))
    @orders = @orders.where(user: current_user) unless current_user.has_role? :admin

    @day_menu = DayMenu.actual(params[:date])

    respond_with @orders
  end

  def new
    @order = Order.new
    @date = DateTime.now
    @items = DayMenu.actual(@date).items

    respond_with @order
  end

  def create
    @order = current_user.orders.build(order_params)
    @date = DateTime.now
    @items = DayMenu.actual(@date).items

    @order.save
    respond_with @order, location: orders_path
  end

  private

  def order_params
    params.require(:order).permit(item_ids: [])
  end

  def only_one_order!
    unless current_user.today_orders.empty?
      flash[:alert] = 'Sorry only one order par day!'
      redirect_to orders_path
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def had_order?
    (current_user.has_role? :admin) && (@date.to_date == Date.today) && @orders.where(user: current_user).empty?
  end
end

app/views/orders/_form.html.slim
h1.text-center = @date.strftime('%A') + ' orders'
= simple_form_for @order do |f|
  .row
    - Menu.all.each do |m|
      .col-md-4
        = f.association :items, label: m.name, multiple: false, collection: @items.where(menu: m), label_method: lambda { |item| "#{item.name} " "#{ number_to_currency(item.price,  unit: "₽ ", precision: 0)} "}
    
  = f.button :submit

app/views/orders/_order.html.slim
h1 = 'Thanks for order ' + " #{order.user.name.capitalize}" + ' enjoy your lunch!!!'

ul
  - order.item_associations.each do |item_association|
    li
      = item_association.item.name + ': '
      = number_to_currency(item_association.item.price,  unit: "₽ ", precision: 0)
h2 Total Price #{number_to_currency(order.total,  unit: "₽ ", precision: 0)}

app/views/orders/index.html.slim
h1.text-center
  = @day_menu.blank? ? 'No Menu for ' :  'Menu for '
  = @date.strftime('%A %d.%m.%Y')
hr

- if @day_menu.present?
  .row
    = render 'day_menus/day_menu', day_menu: @day_menu

  h1.text-center
    = @orders.blank? ? 'No order' : ''

  - if @orders.present?
    - if had_order?
      h2.text-center = 'One order par day Thanks'
    = render @orders  
  - else
    - if @date.to_date == Date.today
      h2.text-center = link_to 'Place your order', new_order_path, class: 'btn btn-lg btn-success'

app/views/orders/new.html.slim
= render 'form'